const PROMPTS = [
  // --- Creative Writing (35) ---
  "Write a short story about someone who discovers a door in their house they have never noticed before.",
  "Describe your ideal morning from the moment you wake up, using all five senses.",
  "Write about a conversation between two strangers stuck in an elevator.",
  "Imagine you wake up tomorrow and everyone has forgotten who you are. What do you do?",
  "Write a letter to your future self, ten years from now.",
  "Describe a meal that changed your life, real or imagined.",
  "Write about a character who can only tell the truth for one day.",
  "Create a story that takes place entirely in a waiting room.",
  "Write about the last person on Earth who still uses a landline phone.",
  "Describe a city that exists only at night and disappears at dawn.",
  "Write a story where the main character discovers their hobby is actually a superpower.",
  "Imagine a world where music is illegal. Write about someone who plays anyway.",
  "Write about two old friends who meet after twenty years of silence.",
  "Describe a storm from the perspective of a tree.",
  "Write a story that begins and ends with the same sentence.",
  "Create a character who collects something unusual and explain why.",
  "Write about a journey where the destination turns out to be less important than the path.",
  "Describe an abandoned building and invent its history.",
  "Write a conversation between a parent and child about something the child does not yet understand.",
  "Imagine you can speak to animals for one hour. What happens?",
  "Write about a gift that arrives with no return address.",
  "Create a story set during a power outage in a big city.",
  "Write about a librarian who discovers a book that writes itself.",
  "Describe the most beautiful thing you have ever seen, real or imagined.",
  "Write about someone who finds a message in a bottle, but the message is for them specifically.",
  "Create a story where the weather reflects the main character's emotions exactly.",
  "Write about a tradition that only your family has.",
  "Describe an invention that the world desperately needs but does not have yet.",
  "Write a scene where someone says goodbye without using the word goodbye.",
  "Imagine you can relive one hour of your life. Which hour and why?",
  "Write about a neighborhood where every house has a secret.",
  "Create a character who is afraid of something ordinary and explain how they cope.",
  "Write about a photograph that tells a story nobody expected.",
  "Describe what silence sounds like in three different places.",
  "Write about a small act of kindness that had enormous consequences.",

  // --- Reflective / Personal (35) ---
  "What is one belief you held five years ago that you no longer hold? What changed your mind?",
  "Describe a failure that taught you more than any success ever did.",
  "What does home mean to you, beyond a physical place?",
  "Write about a time you were completely wrong about someone.",
  "What would you do differently if you knew nobody was watching or judging?",
  "Describe the most difficult conversation you have ever had.",
  "What skill do you wish you had started learning earlier in life?",
  "Write about a moment when you felt truly brave.",
  "What does success look like to you right now versus five years ago?",
  "Describe a relationship that shaped who you are today.",
  "What are you avoiding right now, and why?",
  "Write about a time when doing nothing was the hardest thing to do.",
  "What is the most valuable piece of advice you have ever ignored?",
  "Describe a place that no longer exists but lives clearly in your memory.",
  "What would you tell your younger self about worry?",
  "Write about something you are proud of that nobody else knows about.",
  "What does courage look like in everyday life?",
  "Describe a decision that felt small at the time but changed everything.",
  "What have you learned about yourself from being alone?",
  "Write about a promise you made to yourself and whether you kept it.",
  "What is one thing you would change about how you spend your time?",
  "Describe the difference between being busy and being productive in your own life.",
  "What is a question you are afraid to answer honestly?",
  "Write about a moment when you realized you had grown up.",
  "What does patience mean to you, and when is it hardest to practice?",
  "Describe a habit you want to break and why it persists.",
  "What is the kindest thing someone has done for you that they probably do not remember?",
  "Write about a time when your perspective was limited and how you came to see it differently.",
  "What role does fear play in your daily decisions?",
  "Describe what freedom means to you in practical terms.",
  "What is something you wish more people understood about you?",
  "Write about the relationship between comfort and growth in your own experience.",
  "What are three things you are grateful for that you usually take for granted?",
  "Describe a teacher, mentor, or figure who influenced you without trying to.",
  "What would your life look like if you optimized for peace instead of achievement?",

  // --- Analytical / Argumentative (30) ---
  "Choose a technology you use daily and argue both for and against its impact on society.",
  "Is it better to have a wide range of shallow skills or deep expertise in one area? Make your case.",
  "Should social media platforms be responsible for the mental health of their users? Why or why not?",
  "Argue for or against the idea that remote work is better for most people.",
  "What is the most overrated virtue in modern society, and why?",
  "Is privacy a right or a privilege in the digital age? Defend your position.",
  "Should schools teach financial literacy as a core subject? Make an argument.",
  "Is ambition inherently good, or can it become destructive? Explain with examples.",
  "Argue for or against the statement: reading fiction makes you a better person.",
  "What is more important for a fulfilling life: freedom or security?",
  "Should voting be mandatory? Build your argument carefully.",
  "Is it possible to be truly objective? Analyze with examples.",
  "Argue for or against the idea that competition brings out the best in people.",
  "What would change if the average human lifespan doubled overnight?",
  "Should art be funded by governments, or should it survive on its own merit?",
  "Is it ethical to use artificial intelligence to make hiring decisions? Discuss.",
  "Argue for or against: the best ideas come from constraints, not freedom.",
  "What is the strongest argument against your own political views?",
  "Should public transportation be free for everyone? Why or why not?",
  "Is nostalgia helpful or harmful? Build your case with specific examples.",
  "Argue for or against the idea that everyone should learn to code.",
  "What is the most important problem that most people are ignoring?",
  "Should there be limits on how much wealth one person can accumulate?",
  "Is convenience making us weaker as a society? Defend your position.",
  "Argue for or against: failure should be celebrated as much as success.",
  "What is the difference between wisdom and intelligence, and which matters more?",
  "Should we explore space when there are unsolved problems on Earth?",
  "Is it better to be liked or respected? Build your argument.",
  "Argue for or against: the news does more harm than good.",
  "What would happen if everyone in the world spoke the same language?",

  // --- Observational / Descriptive (20) ---
  "Describe the view from the nearest window. What do you notice that you usually overlook?",
  "Write about the sounds you can hear right now, from loudest to softest.",
  "Describe a stranger you saw recently without making any assumptions about their life.",
  "Write about an ordinary object on your desk as if you are seeing it for the first time.",
  "Describe the way light changes in your room over the course of a day.",
  "Write about a walk you take regularly, noticing three things you have never paid attention to before.",
  "Describe the taste and texture of something you ate today in extreme detail.",
  "Write about a building you pass often but have never entered. Imagine what is inside.",
  "Describe your neighborhood as if you were explaining it to someone who has never visited your country.",
  "Write about the difference between how a place looks in the morning versus at night.",
  "Describe a piece of clothing you own and the memories attached to it.",
  "Write about the way someone you know laughs, and what it reveals about them.",
  "Describe a tree you can see or remember well. Give it a personality.",
  "Write about the feeling of a specific weather condition: not what it looks like, but how it feels.",
  "Describe a crowded place using only sounds and smells, no visual descriptions.",
  "Write about an everyday ritual — making coffee, commuting, washing dishes — as if it were sacred.",
  "Describe the hands of someone you love without saying whose hands they are.",
  "Write about a color without naming it. Make the reader guess which one.",
  "Describe a room that reveals everything about the person who lives in it.",
  "Write about a moment of transition: the seconds between one state and another.",

  // --- Hypothetical / Thought Experiment (15) ---
  "If you could institute one rule that everyone in the world had to follow, what would it be and why?",
  "Imagine you are given one billion dollars but must spend it all in one year. What do you do?",
  "If you could have dinner with any person, living or dead, who would it be and what would you ask?",
  "What would you do if you were invisible for a day?",
  "Imagine a world without the internet. Describe a typical day in that world.",
  "If you could master any skill instantly, which would you choose and how would your life change?",
  "What would you do if you knew you could not fail?",
  "Imagine you wake up in the year 2200. Describe what you see.",
  "If every job paid the same salary, what would you choose to do?",
  "What would change about society if humans did not need to sleep?",
  "If you could send a message to every person on Earth at once, what would you say?",
  "Imagine you discover a parallel universe where you made different life choices. Describe that version of you.",
  "If you could eliminate one human emotion, which would it be and what would the consequences be?",
  "What would you build if you had unlimited resources and five years?",
  "If memories could be bought and sold, would you participate? Why or why not?",
];
